"""Tests for Cursor reverse conversion."""

import pytest
from pathlib import Path

from agent_bridge.converters._cursor_impl import (
    apply_reverse_capture_cursor,
    reverse_convert_cursor,
)
from agent_bridge.core.types import CapturedFile, CaptureStatus
from tests.conftest import strip_and_normalize


def test_reverse_cursor_agent(tmp_project_with_ide_outputs):
    """Forward .agent/agents/orchestrator.md -> .cursor/agents/orchestrator.md
    then reverse -> body must match."""
    project = tmp_project_with_ide_outputs
    agent_dir = project / ".agent"
    cursor_agent = project / ".cursor" / "agents" / "orchestrator.md"
    assert cursor_agent.exists()

    original = (agent_dir / "agents" / "orchestrator.md").read_text()
    original_body = strip_and_normalize(original)

    captured = CapturedFile(
        ide_path=cursor_agent,
        agent_path=agent_dir / "agents" / "orchestrator.md",
        status=CaptureStatus.NEW,
        ide_name="cursor",
    )
    apply_reverse_capture_cursor(captured, project, agent_dir)

    reversed_content = (agent_dir / "agents" / "orchestrator.md").read_text()
    reversed_body = strip_and_normalize(reversed_content)
    assert original_body == reversed_body


def test_reverse_cursor_mdc_rule_always_apply(tmp_project_with_ide_outputs):
    """clean-code skill -> .cursor/rules/clean-code.mdc (alwaysApply:true, no globs)
    reverse -> .agent/rules/clean-code.md."""
    project = tmp_project_with_ide_outputs
    agent_dir = project / ".agent"
    mdc_file = project / ".cursor" / "rules" / "clean-code.mdc"
    if not mdc_file.exists():
        pytest.skip("clean-code.mdc not generated (MDC_RULES_CONFIG may differ)")

    files = reverse_convert_cursor(project, agent_dir, verbose=False)
    rule_files = [f for f in files if "rules" in str(f.agent_path)]
    assert any("clean-code" in str(f.agent_path) for f in rule_files)


def test_reverse_cursor_mdc_rule_with_globs(tmp_project):
    """Manually create .cursor/rules/python-patterns.mdc with globs
    reverse -> .agent/skills/python-patterns/SKILL.md."""
    rules_dir = tmp_project / ".cursor" / "rules"
    rules_dir.mkdir(parents=True, exist_ok=True)
    mdc_content = """---
description: Python patterns
globs: **/*.py
alwaysApply: false
---

# Python Patterns

Keep Python code clean.
"""
    (rules_dir / "python-patterns.mdc").write_text(mdc_content)

    agent_dir = tmp_project / ".agent"
    agent_dir.mkdir(parents=True, exist_ok=True)
    (agent_dir / "skills").mkdir(exist_ok=True)

    files = reverse_convert_cursor(tmp_project, agent_dir, verbose=False)
    python_files = [f for f in files if "python-patterns" in str(f.agent_path)]
    assert len(python_files) == 1
    assert "skills" in str(python_files[0].agent_path)


def test_reverse_cursor_skill(tmp_project_with_ide_outputs):
    """Non-standard skill -> .cursor/skills/custom/SKILL.md
    reverse -> .agent/skills/custom/SKILL.md."""
    project = tmp_project_with_ide_outputs
    skills_dir = project / ".cursor" / "skills"
    if not skills_dir.exists():
        pytest.skip("No cursor skills")
    skill_dirs = [d for d in skills_dir.iterdir() if d.is_dir()]
    if not skill_dirs:
        pytest.skip("No skill dirs in cursor")
    skill_dir = skill_dirs[0]
    skill_md = skill_dir / "SKILL.md"
    assert skill_md.exists()

    agent_dir = project / ".agent"
    captured = CapturedFile(
        ide_path=skill_md,
        agent_path=agent_dir / "skills" / skill_dir.name / "SKILL.md",
        status=CaptureStatus.NEW,
        ide_name="cursor",
    )
    apply_reverse_capture_cursor(captured, project, agent_dir)

    dest = agent_dir / "skills" / skill_dir.name / "SKILL.md"
    assert dest.exists()


def test_reverse_cursor_strips_credit_line(tmp_project_with_ide_outputs):
    """Verify the 'Generated by Agent Bridge' credit line is removed."""
    project = tmp_project_with_ide_outputs
    cursor_agent = project / ".cursor" / "agents" / "orchestrator.md"
    if not cursor_agent.exists():
        pytest.skip("No cursor agents")
    content = cursor_agent.read_text()
    assert "Generated by" in content and "Agent Bridge" in content

    agent_dir = project / ".agent"
    captured = CapturedFile(
        ide_path=cursor_agent,
        agent_path=agent_dir / "agents" / "orchestrator.md",
        status=CaptureStatus.NEW,
        ide_name="cursor",
    )
    apply_reverse_capture_cursor(captured, project, agent_dir)

    reversed_content = (agent_dir / "agents" / "orchestrator.md").read_text()
    assert "Generated by [Agent Bridge]" not in reversed_content


def test_reverse_cursor_skips_project_instructions(tmp_project_with_ide_outputs):
    """project-instructions.mdc should NOT be captured (auto-generated)."""
    project = tmp_project_with_ide_outputs
    agent_dir = project / ".agent"
    files = reverse_convert_cursor(project, agent_dir, verbose=False)
    project_instruction_files = [f for f in files if "project-instructions" in str(f.ide_path)]
    assert len(project_instruction_files) == 0


def test_reverse_cursor_handles_user_created_rule(tmp_project):
    """User manually creates .cursor/rules/my-custom.mdc (not in meta).
    Should be captured as 'new' file."""
    rules_dir = tmp_project / ".cursor" / "rules"
    rules_dir.mkdir(parents=True, exist_ok=True)
    (rules_dir / "my-custom.mdc").write_text("""---
description: Custom rule
globs:
alwaysApply: true
---

# Custom

User content.
""")

    agent_dir = tmp_project / ".agent"
    agent_dir.mkdir(parents=True, exist_ok=True)
    (agent_dir / "rules").mkdir(exist_ok=True)

    files = reverse_convert_cursor(tmp_project, agent_dir, verbose=False)
    custom_files = [f for f in files if "my-custom" in str(f.ide_path)]
    assert len(custom_files) == 1
    assert custom_files[0].agent_path == agent_dir / "rules" / "my-custom.md"
