"""Shared frontmatter parsing and generation utilities."""

import re
from typing import Dict, Optional, Tuple

import yaml

_RE_FRONTMATTER = re.compile(r"^---\n(.*?)\n---\n*", re.DOTALL)


class FrontmatterParser:
    """Parse and generate YAML/MDC frontmatter in markdown files."""

    @staticmethod
    def extract(content: str) -> Tuple[Optional[Dict], str]:
        """
        Extract frontmatter dict and body from content.

        Returns:
            (metadata_dict or None, body_without_frontmatter)
        """
        content = content.replace("\r\n", "\n")
        match = _RE_FRONTMATTER.match(content)
        if not match:
            return None, content
        try:
            metadata = yaml.safe_load(match.group(1))
            return (metadata if isinstance(metadata, dict) else None), content[match.end():]
        except yaml.YAMLError:
            return None, content[match.end():]

    @staticmethod
    def generate(metadata: Dict, body: str, style: str = "yaml") -> str:
        """
        Generate content with frontmatter prepended.

        Args:
            metadata: Dict to serialize as frontmatter
            body: Markdown body (without frontmatter)
            style: 'yaml' (default) or 'mdc' (key: value lines, no quoting)

        Returns:
            Full content string with frontmatter block
        """
        if style == "mdc":
            lines = ["---"]
            for k, v in metadata.items():
                lines.append(f"{k}: {v}")
            lines.append("---")
            fm_str = "\n".join(lines)
        else:
            fm_str = f"---\n{yaml.dump(metadata, default_flow_style=False, allow_unicode=True, sort_keys=False, width=1000).rstrip()}---"
        return f"{fm_str}\n\n{body.strip()}\n"

    @staticmethod
    def strip(content: str) -> str:
        """Remove frontmatter block from content, returning only the body."""
        return _RE_FRONTMATTER.sub("", content.replace("\r\n", "\n"))

    @staticmethod
    def strip_credit_line(content: str) -> str:
        """Remove 'Generated by Agent Bridge' credit line from content."""
        return re.sub(
            r"\n*---\n\*Generated by \[Agent Bridge\].*?\*\n?",
            "",
            content,
            flags=re.IGNORECASE,
        ).strip()
